/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-04-24 23:05:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import algo.CipherHelper;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.Random;

public final class reencyp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("algo.CipherHelper");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("  <title>Proxy Encryption</title>\n");
      out.write("\n");
      out.write("  <!-- Favicons -->\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("  <!-- Google Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Raleway:300,400,500,600,700|Poppins:300,400,500,600,700\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Vendor CSS Files -->\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Template Main CSS File -->\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("    html, body {\n");
      out.write("      height: 100%;\n");
      out.write("      margin: 0;\n");
      out.write("      background-color: lightyellow; /* consistent background color */\n");
      out.write("    }\n");
      out.write("    #hero {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      height: 100vh;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("    #footer {\n");
      out.write("      text-align: center;\n");
      out.write("      color: purple;\n");
      out.write("      background-color: lightblue;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .form-control {\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("   \n");
      out.write("    .form-box {\n");
      out.write("      padding: 20px;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Header -->\n");
      out.write("  <header id=\"header\" class=\"fixed-top d-flex align-items-center\" style=\"background-color: lightblue\">\n");
      out.write("    <div class=\"container d-flex justify-content-between\" >\n");
      out.write("      <h1 class=\"logo\"><a href=\"index.html\">Proxy<span style=\"color:purple;\">Re-Encryption</span></a></h1>\n");
      out.write("      <nav id=\"navbar\" class=\"navbar\">\n");
      out.write("        <ul>\n");
      out.write("          <li><a class=\"nav-link scrollto \" href=\"chome.jsp\">Home</a></li>\n");
      out.write("          <li><a class=\"nav-link scrollto \" href=\"uplo.jsp\">Uploaded Files</a></li>\n");
      out.write("          <li><a class=\"nav-link scrollto active\" href=\"reencyp.jsp\">Re-Encryption Request</a></li>\n");
      out.write("          <li><a class=\"nav-link scrollto \" href=\"sendkey.jsp \">Send Key </a></li>\n");
      out.write("          <li><a class=\"nav-link scrollto \" href=\"authowneranduser.jsp\">Authorize Owners and Users</a></li>\n");
      out.write("          <li><a class=\"nav-link scrollto \" href=\"index.html\">Logout</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <i class=\"bi bi-list mobile-nav-toggle\"></i>\n");
      out.write("      </nav>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("      <!-- ======= Hero Section ======= -->\n");
      out.write("  <section >\n");
      out.write("\n");
      out.write("   \n");
      out.write("\n");
      out.write("         <br>\n");
      out.write("         <br>\n");
      out.write("      \n");
      out.write("                    <style>\n");
      out.write("                        table,tr,th,td{\n");
      out.write("                            border: 1px solid black;\n");
      out.write("                            border-collapse:collapse;\n");
      out.write("                            padding:5px;\n");
      out.write("                            margin-top:- 200px;\n");
      out.write("                        }\n");
      out.write("                        th{\n");
      out.write("                    background-color: #0dcaf0;\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                        </style>\n");
      out.write("                         <h2 style=\"  color:#3498db ; text-align: center; font-size: 25px; font-weight: bolder; margin-left:-50px; \">View Re-Encryption File Request!!</h2>\n");
      out.write("                          <br>\n");
      out.write("                        <br>\n");
      out.write("                        <br>\n");
      out.write("                         \n");
      out.write("                    <table style=\" margin-left: 400px; margin-bottom: 100px;\">\n");
      out.write("                              <tr>\n");
      out.write("                            <th>ID</th>\n");
      out.write("                            <th>Username</th>\n");
      out.write("                            <th>Email</th>\n");
      out.write("                           <th>Keyword</th>\n");
      out.write("                            <th>File</th>\n");
      out.write("                            <th>Status</th>\n");
      out.write("                            \n");
      out.write("                               </tr>\n");
      out.write("                      ");
   
                          
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/proxy","root","Sameer@786");
                        PreparedStatement query=con.prepareStatement("select * from porequest ");
                        ResultSet rs=query.executeQuery();
                        System.out.println(query);
                        while(rs.next()){
                         
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print(rs.getString("id"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getString("user"));
      out.write("</td>  \n");
      out.write("                            <td>");
      out.print(rs.getString("email"));
      out.write("</td>\n");
      out.write("                            <td>");
      out.print(rs.getString("keyword"));
      out.write("</td> \n");
      out.write("                            <td style=\" color: #00cae3;  font-weight: bold;\"> ");
      out.print(rs.getString("file"));
      out.write("</td>\n");
      out.write("                             \n");
      out.write("                            <td > <a href=\"filacpt1.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" style=\"color:  #6600cc; font-weight:bold;\">");
      out.print(rs.getString("status"));
      out.write("</a></td></tr>\n");
      out.write("                             \n");
      out.write("                        ");
}
      out.write("</table> </form>  \n");
      out.write("                    <br><br><br><br></div></div></div>  \n");
      out.write("\n");
      out.write("      <br>     \n");
      out.write("<br><br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>     \n");
      out.write("<br><br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  </section><!-- End Hero -->                                              \n");
      out.write("                                              \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Footer -->\n");
      out.write("  <footer id=\"footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <p>Copyright © 2024 SameerKhan</p>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\n");
      out.write("\n");
      out.write("  <!-- Vendor JS Files -->\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Template Main JS File -->\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
