/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-04-18 07:10:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1713424146707L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1713424146711L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html >\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"csss1.css\" />\n");
      out.write("\n");
      out.write("<title>ProxyReEncryption</title>\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"csss2.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<table align=\"left\">\n");
      out.write("	<tr>\n");
      out.write("		\n");
      out.write("	</tr>\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<font size=\"5\"><center><H2>Secure Cloud Storage with Proxy Re-Encryption System</H2></center></font>\n");
      out.write("\n");
      out.write("<div class=\"drop\">\n");
      out.write("\n");
      out.write("<center><ul class=\"drop_menu\">\n");
      out.write("<li class=\"\">\n");
      out.write("                        <a href=\"index.jsp\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("                     <li class=\"page-scroll\">\n");
      out.write("                        <a href=\"DataOwner.jsp\">Data Owner</a>\n");
      out.write("                    </li>\n");
      out.write("					<li class=\"page-scroll\">\n");
      out.write("                        <a href=\"User.jsp\">User</a>\n");
      out.write("                    </li>\n");
      out.write("					\n");
      out.write("                   \n");
      out.write("					<li class=\"page-scroll\">\n");
      out.write("                        <a href=\"login.jsp\">CSP</a>\n");
      out.write("								\n");
      out.write("									<!--<ul>\n");
      out.write("										<li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("										<li><a href=\"register.jsp\">Registration</a></li>\n");
      out.write("								    </ul>-->\n");
      out.write("							\n");
      out.write("                    </li>\n");
      out.write("</ul>\n");
      out.write("</center></div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write(".footer-inner{\n");
      out.write("	background-color: grey;\n");
      out.write("	display: block;\n");
      out.write("	text-align:right;\n");
      out.write("}\n");
      out.write(".footer-ul{\n");
      out.write("	list-style-type: none;\n");
      out.write("	 margin: 10px;\n");
      out.write("    padding: 10px;\n");
      out.write("}\n");
      out.write(".footer-ul li{\n");
      out.write("	display: inline;\n");
      out.write("	padding-right:10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write('\n');

String msg = request.getParameter("msgg");
if(msg != null){
out.println("<script>alert('Product Details Added.........')</script>");
}

      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"signup\" align=\"\">\n");
      out.write("             <br><br><br><br>\n");
      out.write("		<section id=\"contact\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                   <h2>Registration</h2>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2\">\n");
      out.write("				\n");
      out.write("					<form action=\"register1.jsp\" method=\"post\" id=\"demoForm\" class=\"demoForm\" class=\"form-group\" id=\"contact-form\">\n");
      out.write("						\n");
      out.write("						<br>\n");
      out.write("						<label>	Name</label><div class=\"row\">\n");
      out.write("							<div class=\"col-md-4\">\n");
      out.write("								<input type=\"text\" name=\"nm\" pattern=\"[A-Za-z]+\"  class=\"form-control\"></div>\n");
      out.write("						</div><br>\n");
      out.write("						<label>Username</label><div class=\"row\">\n");
      out.write("							<div class=\"col-md-4\">\n");
      out.write("								<input type=\"text\" name=\"unm\" class=\"form-control\"></div>\n");
      out.write("						</div><br>\n");
      out.write("						\n");
      out.write("						\n");
      out.write("						<label>	Password</label><div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("								<input type=\"password\" name=\"pwd\"    class=\"form-control\" required></div>\n");
      out.write("						</div><br>\n");
      out.write("						\n");
      out.write("						<label>Email</label><div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("								<input type=\"email\" name=\"eid\"   class=\"form-control\"  required></div>\n");
      out.write("						</div><br>\n");
      out.write("						<label>Gender</label><div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("								<input type=\"radio\" name=\"gen\" value=\"male\">Male&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"radio\" name=\"gen\"   value=\"female\">FeMale</div>\n");
      out.write("						</div><br>\n");
      out.write("						\n");
      out.write("						<label>Contact N0</label><div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("								<input type=\"text\" name=\"cno\"   class=\"form-control\"  required></div>\n");
      out.write("						</div><br>\n");
      out.write("\n");
      out.write("						<label>Department</label><div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("								<select name=\"category\" style=\"width: 150px\">\n");
      out.write("    <option value=\"Engineering\">Engineering</option>\n");
      out.write("    <option value=\"Accounting\">Accounting</option>\n");
      out.write("    <option value=\"Marketing\">Marketing</option> \n");
      out.write("</select></div><br><br><br>\n");
      out.write("&nbsp;&nbsp;<label>SubDepartment</label><div class=\"row\">\n");
      out.write("<div class=\"col-md-4\">\n");
      out.write("<select name=\"choices[]\" id=\"choices\" style=\"width: 150px\" >\n");
      out.write("</select></div></div><br>\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"row\">\n");
      out.write("                                <input type=\"submit\" class=\"btn btn-success btn-lg\" value=\"Register\">\n");
      out.write("                            </div>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("					</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("	</div>\n");
      out.write("				<br><br><br><br>\n");
      out.write("	");
      out.write("<html >\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css1.css\" />\n");
      out.write("<title>S2B</title>\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"css2.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write(".footer-inner{\n");
      out.write("	background-color: grey;\n");
      out.write("	display: block;\n");
      out.write("	text-align:right;\n");
      out.write("}\n");
      out.write(".footer-ul{\n");
      out.write("	list-style-type: none;\n");
      out.write("	 margin: 10px;\n");
      out.write("    padding: 10px;\n");
      out.write("}\n");
      out.write(".footer-ul li{\n");
      out.write("	display: inline;\n");
      out.write("	padding-right:10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<div class=\"footer\">\n");
      out.write("<div style=\"width:100%\" class=\"footer-inner\">\n");
      out.write("<ul class=\"footer-ul\">\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("/*\n");
      out.write("From JavaScript and Forms Tutorial at dyn-web.com\n");
      out.write("Find information and updates at http://www.dyn-web.com/tutorials/forms/\n");
      out.write("*/\n");
      out.write("\n");
      out.write("// removes all option elements in select list \n");
      out.write("// removeGrp (optional) boolean to remove optgroups\n");
      out.write("function removeAllOptions(sel, removeGrp) {\n");
      out.write("    var len, groups, par;\n");
      out.write("    if (removeGrp) {\n");
      out.write("        groups = sel.getElementsByTagName('optgroup');\n");
      out.write("        len = groups.length;\n");
      out.write("        for (var i=len; i; i--) {\n");
      out.write("            sel.removeChild( groups[i-1] );\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    len = sel.options.length;\n");
      out.write("    for (var i=len; i; i--) {\n");
      out.write("        par = sel.options[i-1].parentNode;\n");
      out.write("        par.removeChild( sel.options[i-1] );\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function appendDataToSelect(sel, obj) {\n");
      out.write("    var f = document.createDocumentFragment();\n");
      out.write("    var labels = [], group, opts;\n");
      out.write("    \n");
      out.write("    function addOptions(obj) {\n");
      out.write("        var f = document.createDocumentFragment();\n");
      out.write("        var o;\n");
      out.write("        \n");
      out.write("        for (var i=0, len=obj.text.length; i<len; i++) {\n");
      out.write("            o = document.createElement('option');\n");
      out.write("            o.appendChild( document.createTextNode( obj.text[i] ) );\n");
      out.write("            \n");
      out.write("            if ( obj.value ) {\n");
      out.write("                o.value = obj.value[i];\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            f.appendChild(o);\n");
      out.write("        }\n");
      out.write("        return f;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    if ( obj.text ) {\n");
      out.write("        opts = addOptions(obj);\n");
      out.write("        f.appendChild(opts);\n");
      out.write("    } else {\n");
      out.write("        for ( var prop in obj ) {\n");
      out.write("            if ( obj.hasOwnProperty(prop) ) {\n");
      out.write("                labels.push(prop);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        for (var i=0, len=labels.length; i<len; i++) {\n");
      out.write("            group = document.createElement('optgroup');\n");
      out.write("            group.label = labels[i];\n");
      out.write("            f.appendChild(group);\n");
      out.write("            opts = addOptions(obj[ labels[i] ] );\n");
      out.write("            group.appendChild(opts);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    sel.appendChild(f);\n");
      out.write("}\n");
      out.write("\n");
      out.write("// anonymous function assigned to onchange event of controlling select list\n");
      out.write("document.forms['demoForm'].elements['category'].onchange = function(e) {\n");
      out.write("    // name of associated select list\n");
      out.write("    var relName = 'choices[]';\n");
      out.write("    \n");
      out.write("    // reference to associated select list \n");
      out.write("    var relList = this.form.elements[ relName ];\n");
      out.write("    \n");
      out.write("    // get data from object literal based on selection in controlling select list (this.value)\n");
      out.write("    var obj = Select_List_Data[ relName ][ this.value ];\n");
      out.write("    \n");
      out.write("    // remove current option elements\n");
      out.write("    removeAllOptions(relList, true);\n");
      out.write("    \n");
      out.write("    // call function to add optgroup/option elements\n");
      out.write("    // pass reference to associated select list and data for new options\n");
      out.write("    appendDataToSelect(relList, obj);\n");
      out.write("};\n");
      out.write("\n");
      out.write("// object literal holds data for optgroup/option elements\n");
      out.write("var Select_List_Data = {\n");
      out.write("    \n");
      out.write("    // name of associated select list\n");
      out.write("    'choices[]': {\n");
      out.write("        \n");
      out.write("        // names match option values in controlling select list\n");
      out.write("       Engineering: {\n");
      out.write("            // optgroup labe\n");
      out.write("                text: ['Designing','Programming','Testing'],\n");
      out.write("                value: ['Designing','Programming','Testing']\n");
      out.write("            },\n");
      out.write("   \n");
      out.write("       Accounting: {\n");
      out.write("            // example without optgroups\n");
      out.write("            text: ['Payroll','Investment'],\n");
      out.write("            value: ['Payroll', 'Investment']\n");
      out.write("        },\n");
      out.write("			Marketing: {\n");
      out.write("            // example without optgroups\n");
      out.write("            text: ['Financial','H.R'],\n");
      out.write("            value: ['Financial','H.R']\n");
      out.write("        },\n");
      out.write("		\n");
      out.write("		\n");
      out.write("        mrktaaaaa: {\n");
      out.write("            'Download Demos': {\n");
      out.write("                // example without values\n");
      out.write("                text: ['Iframes', 'PHP to JS', 'Unobtrusive JS']\n");
      out.write("            },\n");
      out.write("            \n");
      out.write("            'No Download': {\n");
      out.write("                text: ['Object Literals', 'Initializing JS', 'JS Errors']\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("};\n");
      out.write("\n");
      out.write("// populate associated select list when page loads\n");
      out.write("window.onload = function() {\n");
      out.write("    var form = document.forms['demoForm'];\n");
      out.write("    \n");
      out.write("    // reference to controlling select list\n");
      out.write("    var sel = form.elements['category'];\n");
      out.write("    sel.selectedIndex = 0;\n");
      out.write("    \n");
      out.write("    // name of associated select list\n");
      out.write("    var relName = 'choices[]';\n");
      out.write("    // reference to associated select list\n");
      out.write("    var rel = form.elements[ relName ];\n");
      out.write("    \n");
      out.write("    // get data for associated select list passing its name\n");
      out.write("    // and value of selected in controlling select list\n");
      out.write("    var data = Select_List_Data[ relName ][ sel.value ];\n");
      out.write("    \n");
      out.write("    // add options to associated select list\n");
      out.write("    appendDataToSelect(rel, data);\n");
      out.write("};\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("			");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
